config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admins/sessions' }
  root to: 'top#index'
  resources :instruments, only: %i[index new create edit update destroy]
  resources :performers
  resources :monthly_schedules, only: %i[show edit update], param: :date

  namespace :setting do
    resource :weekly_posts, only: %i[edit update]
  end

  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :instruments, only: %i[index show]
      resources :performers, only: %i[index show]
      get 'monthly_schedules/:date', controller: :schedules, action: :index
      resources :schedules, only: %i[show], param: :date
      resource :todays_article, only: %i[show]
    end
  end
end

app/models/performer.rb
class Performer < ApplicationRecord
  INTRODUCTION_TRUNCATE_LENGTH = 50

  has_many :attendances
  belongs_to :instrument
  delegate :name, to: :instrument, prefix: :instrument

  validates :name, :instrument_id, presence: true
  validates :name, length: { maximum: 255 }
  validates :regular, inclusion: { in: [true, false] }
  validates :icon_url, :image_url, format: /\A#{URI.regexp(%w[http https])}\z/, allow_blank: true

  scope :regulars, lambda {
    where(regular: true)
  }
end

app/controllers/api/v1/performers_controller.rb
module Api
  module V1
    class PerformersController < Api::V1::BaseController
      def index
        performers = if params[:all].to_i == 1
                       Performer.all
                     else
                       Performer.regulars
                     end
        performers = performers.where(instrument_id: params[:instrument_id]) if params[:instrument_id]
        render json: performers
      end

      def show
        performer = Performer.find(params[:id])
        render json: performer
      end
    end
  end
end

app/controllers/performers_controller.rb
class PerformersController < ApplicationController
  before_action :set_performer, only: %i[show edit update destroy]

  def index
    @performers = Performer.all.includes(:instrument)
  end

  def show; end

  def new
    @performer = Performer.new
  end

  def create
    @performer = Performer.new(create_update_params)
    if @performer.save
      redirect_to performer_path(@performer), notice: '演奏者の作成に成功しました'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @performer.update(create_update_params)
      redirect_to performer_path(@performer), notice: '演奏者の更新に成功しました'
    else
      render :edit
    end
  end

  def destroy
    if @performer.destroy
      redirect_to performers_path, notice: '演奏者の削除に成功しました'
    else
      render :index
    end
  end

  private

  def set_performer
    @performer = Performer.find(params[:id])
  end

  def create_update_params
    params.require(:performer).permit(:name, :introduction, :instrument_id, :regular, :image_url, :icon_url)
  end
end

app/views/performers/_form.html.erb
<%= form_for performer do |f| %>
  <%= render partial: 'layouts/error_messages', locals: {object: f.object} %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :instrument_id %>
    <%= f.collection_select(:instrument_id, Instrument.all, :id, :name, {}, { class: 'form-control' }) %>
  </div>

  <div class="form-group">
    <%= f.label :regular %>
    <%= f.check_box(:regular, {class: 'form-control'}) %>
  </div>

  <div class="form-group">
    <%= f.label :introduction %>
    <%= f.text_area :introduction, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :image_url %>
    <%= f.text_field :image_url, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :icon_url %>
    <%= f.text_field :icon_url, class: 'form-control' %>
  </div>

  <div class="form-group text-center">
    <%= f.submit submit_button_value, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/performers/edit.html.erb
<div class="row">
  <div class="col">
    <%= render partial: 'form', locals: {performer: @performer, submit_button_value: '更新する'} %>
  </div>
</div>

<div class="row">
  <div class="col">
    <p class="text-right">
      <%= link_to 'この演奏者を削除する', performer_path(@performer), method: :delete, data: {confirm: '削除します。よろしいですか？'}, class: 'btn btn-danger btn-sm' %>
    </p>
  </div>
</div>

app/views/performers/index.html.erb
<table class="table">
  <thead>
  <tr>
    <th>#</th>
    <th></th>
    <th>名前</th>
    <th>楽器</th>
    <th>レギュラー</th>>
    <th>紹介文</th>
    <th></th>
  </tr>
  </thead>
  <tbody>
  <% @performers.each do |performer| %>
    <tr>
      <td><%= performer.id %></td>
      <td class="p-0"><%= image_tag performer.icon_url, size: '48x48' if performer.icon_url %>
      <td><%= performer.name %></td>
      <td><%= performer.instrument_name %></td>
      <td><%= performer.regular ? 'はい' : 'いいえ' %>
      <td><%= replace_if_blank(performer.introduction, '紹介文がありません').truncate(Performer::INTRODUCTION_TRUNCATE_LENGTH) %></td>
      <td>
        <%= link_to '詳細', performer_path(performer) %>
        <%= link_to '更新', edit_performer_path(performer) %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

<%= link_to '新しく演奏者を作成する', new_performer_path %>

app/views/performers/new.html.erb
<%= render partial: 'form', locals: {performer: @performer, submit_button_value: '作成する'} %>

app/views/performers/show.html.erb
<dl class="row">
  <dt class="col-sm-3">名前</dt>
  <dd class="col-sm-9"><%= @performer.name %></dd>

  <dt class="col-sm-3">楽器</dt>
  <dd class="col-sm-9"><%= @performer.instrument_name %></dd>

  <dt class="col-sm-3">レギュラー?</dt>
  <dd class="col-sm-9"><%= @performer.regular ? 'はい' : 'いいえ' %></dd>

  <dt class="col-sm-3">紹介文</dt>
  <dd class="col-sm-9"><%= replace_if_blank(@performer.introduction, '紹介文がありません') %></dd>

  <dt class="col-sm-3">画像URL</dt>
  <dd class="col-sm-9">
    <%= image_tag @performer.image_url, width: '200' if @performer.image_url %>
    <%= replace_if_blank(@performer.image_url, '画像URLがありません') %>
  </dd>

  <dt class="col-sm-3">アイコンURL</dt>
  <dd class="col-sm-9">
    <%= image_tag @performer.icon_url, width: '200' if @performer.icon_url %>
    <%= replace_if_blank(@performer.icon_url, 'アイコンURLがありません') %>
  </dd>
</dl>

<%= link_to 'この演奏者を更新する', edit_performer_path %>