config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admins/sessions' }
  root to: 'top#index'
  resources :instruments, only: %i[index new create edit update destroy]
  resources :performers
  resources :monthly_schedules, only: %i[show edit update], param: :date

  namespace :setting do
    resource :weekly_posts, only: %i[edit update]
  end

  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :instruments, only: %i[index show]
      resources :performers, only: %i[index show]
      get 'monthly_schedules/:date', controller: :schedules, action: :index
      resources :schedules, only: %i[show], param: :date
      resource :todays_article, only: %i[show]
    end
  end
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  enum state: { undecided: 0, open: 1, closed: 2 }

  has_many :attendances
  has_many :performers, through: :attendances

  validates :date, :state, presence: true
  validates :date, uniqueness: true
  validates :title, length: { maximum: 255 }
  validates :state, inclusion: { in: Schedule.states.keys }

  scope :today, lambda {
    find_by(date: Date.today)
  }

  scope :decided, lambda {
    where.not(state: :undecided)
  }

  scope :select_in_month, lambda { |date|
    range = date.days_in_month
    where(date: range).order(:date)
  }

  def self.select_or_create_in_month(date)
    range = date.days_in_month

    ActiveRecord::Base.transaction do
      range.each { |d| find_or_create_by!(date: d) }
    end
    select_in_month(date)
  end
end

app/controllers/monthly_schedules_controller.rb
class MonthlySchedulesController < ApplicationController
  before_action :set_date

  def show
    @schedules = Schedule.select_or_create_in_month(@date).includes(:performers)
  end

  def edit
    @schedules = Schedule.select_or_create_in_month(@date)
  end

  def update
    ActiveRecord::Base.transaction do
      schedules_params.each do |id, attribute|
        schedule = Schedule.find(id)
        schedule.update!(attribute)
        attendances_update!(schedule)
      end
    end
    redirect_to monthly_schedule_path(@date), notice: 'スケジュールの更新に成功しました'
  end

  private

  def schedules_params
    params.permit(schedule: %i[state title detail]).require(:schedule)
  end

  def attendances_params
    params.permit(schedule: :performer_ids).require(:schedule)
  end

  def attendances_update!(schedule)
    schedule.attendances.each(&:destroy!)
    performer_ids = attendances_params[schedule.id.to_s][:performer_ids].split(',')
    performer_ids.each_with_index do |performer_id, _index|
      schedule.attendances.create!(performer_id: performer_id)
    end
  end

  def set_date
    @date = params[:date].to_date
  end
end

app/views/monthly_schedules/_form_unit.html.erb
<%= fields_for 'schedule[]', schedule do |fi| %>
  <tr>
    <td>
      <%= schedule.date %>
    </td>
    <td>
      <%= ja_week(schedule.date) %>
    </td>
    <td>
      <%= fi.select :state, Schedule.states.keys.map {|k| [k, k]}, {}, { class: 'form-control' } %>
    </td>
    <td>
      <%= fi.text_field :performer_ids, class: 'performer_selector' %>
    </td>
    <td>
      <%= fi.text_field :title, class: 'form-control' %>
    </td>
    <td>
      <%= fi.text_field :detail, class: 'form-control' %>
    </td>
  </tr>
<% end %>

app/views/monthly_schedules/edit.html.erb
<%= form_tag monthly_schedule_path(@date), method: :put do %>
  <table class="table table-condensed table-borderless table-sm">
    <thead>
      <tr>
        <td>日付</td>
        <td>曜日</td>
        <td>状態</td>
        <td>演奏者</td>
        <td>タイトル</td>
        <td>詳細</td>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'form_unit', collection: @schedules, as: :schedule %>
    </tbody>
  </table>
  <div class="form-group text-center">
    <%= submit_tag '更新する', class: 'btn btn-primary' %>
  </div>
<% end %>

<div id='js-performer_list' data-json='<%= Performer.all.to_json(only: [:id, :name]) %>'></div>
<div id='js-schedules' data-json="<%= @schedules.to_json(only: [:id, :date], include: {performers: {only: [:id, :name]}}) %>"></div>
<%= javascript_include_tag 'bootstrap-tagsinput' %>
<%= javascript_include_tag 'typeahead.bundle' %>
<%= javascript_include_tag 'performer_selector' %>
<%= stylesheet_link_tag 'bootstrap-tagsinput' %>

app/views/monthly_schedules/show.html.erb
<div class="row">
  <div class="col">
    <span><%= link_to '＜' + @date.prev_month.strftime('%Y年%m月'), monthly_schedule_path(@date.prev_month) %></span>
  </div>
  <div class="col text-center">
    <h1><%= @date.strftime('%Y年%m月') %></h1>
  </div>
  <div class="col text-right">
    <span><%= link_to @date.next_month.strftime('%Y年%m月') + '＞', monthly_schedule_path(@date.next_month) %></span>
  </div>
</div>

<div class="row">
  <div class="col">
    <table class="table table-sm">
      <thead>
      <tr>
        <td>#</td>
        <td>曜日</td>
        <td>状態</td>
        <td>演奏者</td>
        <td>タイトル</td>
        <td>詳細</td>
      </tr>
      </thead>
      <tbody>
        <% @schedules.each do |schedule| %>
          <tr>
            <td><%= schedule.date %></td>
            <td><%= ja_week(schedule.date) %></td>
            <td><%= schedule.state %></td>
            <td><%= schedule.performers.map{|p| p.name}.join(',') %>
            <td><%= schedule.title %></td>
            <td><%= schedule.detail %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to '更新する', edit_monthly_schedule_path(@date) %>
  </div>
</div>