config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admins/sessions' }
  root to: 'top#index'
  resources :instruments, only: %i[index new create edit update destroy]
  resources :performers
  resources :monthly_schedules, only: %i[show edit update], param: :date

  namespace :setting do
    resource :weekly_posts, only: %i[edit update]
  end

  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :instruments, only: %i[index show]
      resources :performers, only: %i[index show]
      get 'monthly_schedules/:date', controller: :schedules, action: :index
      resources :schedules, only: %i[show], param: :date
      resource :todays_article, only: %i[show]
    end
  end
end

app/models/instrument.rb
class Instrument < ApplicationRecord
  has_many :performers

  validates :name, :color, presence: true
  validates :name, uniqueness: true
  validates :name, length: { maximum: 255 }
  validates :color, format: { with: /\A#([\da-fA-F]{6}|[\da-fA-F]{3})\z/ }
end

app/controllers/api/v1/instruments_controller.rb
module Api
  module V1
    class InstrumentsController < Api::V1::BaseController
      def index
        instruments = Instrument.all
        render json: instruments
      end

      def show
        instrument = Instrument.find(params[:id])
        render json: instrument
      end
    end
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: %i[edit update destroy]

  def index
    @instruments = Instrument.all
  end

  def new
    @instrument = Instrument.new
  end

  def create
    @instrument = Instrument.new(create_update_params)
    if @instrument.save
      redirect_to instruments_path, notice: '楽器の作成に成功しました'
    else
      render :new
    end
  end

  def edit; end

  def update
    if @instrument.update(create_update_params)
      redirect_to instruments_path, notice: '楽器の更新に成功しました'
    else
      render :edit
    end
  end

  def destroy
    if @instrument.destroy
      redirect_to instruments_path, notice: '楽器の削除に成功しました'
    else
      render :index
    end
  end

  private

  def set_instrument
    @instrument = Instrument.find(params[:id])
  end

  def create_update_params
    params.require(:instrument).permit(:name, :color)
  end
end

app/views/instruments/_form.html.erb
<%= form_for instrument do |f| %>
  <%= render partial: 'layouts/error_messages', locals: { object: f.object } %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :color %>
    <%= f.text_field :color, class: 'form-control', placeholder: '#000000' %>
    <p>color-hex: <a href="https://www.color-hex.com/" target="_blank">https://www.color-hex.com/</a></p>
  </div>

  <div class="form-group text-center">
    <%= f.submit submit_button_value, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/instruments/edit.html.erb
<div class="row">
  <div class="col">
    <%= render partial: 'form', locals: {instrument: @instrument, submit_button_value: '更新する'} %>
  </div>
</div>

<div class="row">
  <div class="col">
    <p class="text-right">
      <%= link_to 'この楽器を削除する', instrument_path(@instrument), method: :delete, data: { confirm: '削除します。よろしいですか？' }, class: 'btn btn-danger btn-sm' %>
    </p>
  </div>
</div>

app/views/instruments/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>#</th>
      <th>名前</th>
      <th>テーマカラー</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @instruments.each do |inst| %>
      <tr>
        <td><%= inst.id %></td>
        <td><%= inst.name %></td>
        <td>
          <span style="color: <%= inst.color %>">■</span>
          <%= inst.color %>
        </td>
        <td>
          <%= link_to '更新', edit_instrument_path(inst) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to '新しく楽器を作成する', new_instrument_path %>

app/views/instruments/new.html.erb
<%= render partial: 'form', locals: { instrument: @instrument, submit_button_value: '作成する' } %>