config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { sessions: 'admins/sessions' }
  root to: 'top#index'
  resources :instruments, only: %i[index new create edit update destroy]
  resources :performers
  resources :monthly_schedules, only: %i[show edit update], param: :date

  namespace :setting do
    resource :weekly_posts, only: %i[edit update]
  end

  namespace :api, { format: 'json' } do
    namespace :v1 do
      resources :instruments, only: %i[index show]
      resources :performers, only: %i[index show]
      get 'monthly_schedules/:date', controller: :schedules, action: :index
      resources :schedules, only: %i[show], param: :date
      resource :todays_article, only: %i[show]
    end
  end
end

app/views/layouts/_error_messages.html.erb
<% object.errors.full_messages.each do |message| %>
  <div class="alert alert-danger"><%= message %></div>
<% end %>

app/views/layouts/_setting_sidebar.html.erb
<div class="list-group">
  <%= link_to '投稿', edit_setting_weekly_posts_path, class: list_group_item_class('setting/weekly_posts') %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LiveSchedules</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">

      <div class="row mt-3">
        <div class="col">
          <% if notice %>
            <div class="alert alert-success"><%= notice %></div>
          <% elsif alert %>
            <div class="alert alert-danger"><%= alert %></div>
          <% end %>
        </div>
      </div>

      <% if current_admin %>
      <div class="row mt-2 mb-5">
        <div class="col">
          <nav class="nav nav-pills nav-justified">
            <%= link_to 'スケジュール', monthly_schedule_path(date: Date.today), class: nav_item_class('monthly_schedules') %>
            <%= link_to '演奏者', performers_path, class: nav_item_class('performers') %>
            <%= link_to '楽器', instruments_path, class: nav_item_class('instruments') %>
            <%= link_to 'その他の設定', edit_setting_weekly_posts_path, class: nav_item_class('setting/') %>
            <%= link_to 'ログアウト', destroy_admin_session_path, method: :delete, class: nav_item_class('logout') %>
          </nav>
        </div>
      </div>
      <% end %>

      <div class="row">

        <% if controller.controller_name.in? %w[weekly_posts] %>
          <div class="col-3">
            <%= render partial: 'layouts/setting_sidebar' %>
          </div>
        <% end %>

        <div class="col">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>